Breakpoint specific sizes for off-canvas
foundation/foundation-sites pull request #10428
Opened 2017-07-18 13:47 UTC by SassNinja

This PR add the possibility to define a different off-canvas size for small and medium by replacing the number with a map.

In a current project the off-canvas is supposed to have clearly more width for medium than for small.
But no matter what value I choose (even percentaged or viewport related), it doesn't look good for both breakpoints.
The bottom line is I need two different off-canvas sizes.

The new maps `$offcanvas-sizes` and `$offcanvas-vertical-sizes` replace the prior `$offcanvas-size` and `$offcanvas-vertical-size`. Since I don't consider any custom setting of these deprecated variables I've added warnings that appear during the gulp process.

Alternatively I could leave the variables name untouched and add several conditions to check if it's a number or a map. But imo a warning is better because it isn't much work for the user to update the settings and keeps the code cleaner.

@brettsmason @IamManchanda what do you think about this feature?

2017-07-19 21:51 UTC, kball commented
For backwards compatibility with old settings files, can you have the old variables set up the new ones if they're defined? Can also print a deprecation warning, but it's best if we don't break projects that have the older settings and not the newer.

2017-07-20 12:33 UTC, SassNinja commented
@kball a deprecation warning was already included by me but you're right, still supporting the deprecated settings would not be amiss.

I've updated the PR and take over the values now.

2017-07-21 15:41 UTC, kball commented
Awesome... this is looking good as far as it goes - makes me wonder though if we should make the logic iterate through the sizes (to allow someone to do this for any arbitrary map of breakpoints) rather than explicitly call out small & medium... thoughts?

Also @brettsmason would love your thoughts & review

2017-07-21 15:48 UTC, IamManchanda commented
This is looking cool from outset... let me dig in...

2017-07-21 15:52 UTC, IamManchanda requested changes

2017-07-21 15:52 UTC, IamManchanda commented on scss/settings/_settings.scss
> +  medium: 350px,
Settings.scss is automatically generated! Remove this file changes

2017-07-21 15:58 UTC, IamManchanda approved these changes
Requested one change above ... apart that looks awesome after digging in!

Have tested it out and can confirm that this works great!
Awesome @SassNinja

2017-07-21 19:33 UTC, kball commented on scss/settings/_settings.scss
> +  medium: 350px,
yeah though it's kind of find - it will get overridden anyway.

2017-07-21 19:34 UTC, kball commented
I'm going to merge this as is, because I'd like to get a point release out and want to land on testable set of changes... that said, would really love a new PR that iterates over the breakpoints to allow any set rather than hard coding small & medium

2017-07-21 19:34 UTC, merged