Drilldown method to show any menu
foundation/foundation-sites pull request #10431
Opened 2017-07-19 14:20 UTC by SassNinja

This PR adds the new method `_showMenu` to the drilldown component for opening any (sub)menu in it **without** clicking through every menu on the way to it.

I usually like the drilldown menu because it's a nice and intuitive navi which I often use in the off-canvas. But it has a huge downside: there's currently no method to jump into a specific submenu without clicking through several submenus.

I've also added a visual test in this PR that shows the difference between the the current `_show` and the new `_showMenu`. You'll see what I mean when you check the 'Use current show' checkbox and click the buttons C, B, X (in this order) and then use the back links.
http://localhost:3000/drilldown/drilldown-show-menu.html

The new method is probably a great feature for everyone who needs to e.g. auto open the current page in the drilldown if using it as page navi.

@IamManchanda @kball @brettsmason what do you think?

2017-07-21 16:23 UTC, IamManchanda commented
This is not awesome... this is super awesome !!! Hats off 
Its like deeplinking came into drilldown's :wink: 

cc @kball for merge/review!

2017-07-21 16:23 UTC, IamManchanda approved these changes
:+1:

2017-07-21 16:25 UTC, IamManchanda requested changes

2017-07-21 16:25 UTC, IamManchanda commented on js/foundation.drilldown.js
> +    // }
Remove these comments!

2017-07-21 20:55 UTC, SassNinja commented on js/foundation.drilldown.js
> +    // }
The lines are commented in now. Instead of removing the possiblity to trigger a close event I'm  just not using it in _showMenu anymore.

2017-07-21 21:06 UTC, SassNinja commented
@IamManchanda many thanks for your kindly words! I'm glad to hear this feature is appreciated 😃 

Apart from your requested change (see my comment above) I've made another slight improvement:
The method `_showMenu` has now a second param called `autoFocus` which will prevent the auto focus of the first link in the target (sub)menu if false.
I think this might by helpful in cases where the auto focus is not desired (e.g. if the drilldown is hidden when calling that function). Default remains true.

2017-07-22 16:20 UTC, IamManchanda approved these changes
Seems very Good!

2017-07-25 15:39 UTC, kball commented
Testing through the visual test I see a few issues

1. When I click in using the 'showMenu' option I get some weird focus behavior (the focus ring which is supposed to only show on keyboard nav starts showing on elements within the drilldown.
2. When I keyboard nav around, I seem to occasionally trigger some sort of behavior where the entire drilldown becomes hidden.

Both of these were in Chrome latest (59) on mac

2017-07-25 22:02 UTC, SassNinja commented
@kball thanks for your feedback!

1. That's actually a feature: I've added this auto focus so the user can jump right into the drilldown via keyboard after having clicked the trigger (button). Would you prefer no auto focus by default?
Currently the auto focus may get disabled by explicitly setting the param to false
```javascript
$drilldown.foundation('_showMenu', $menu, false);
``` 
2. Would you describe more detailed how to reproduce this?
But I think I know what you mean. When I click 'Show X', then above the buttons (lose focus) and then press several times the TAB key the drilldown menus get mixed up.
However **this isn't caused by my changes / PR** because it also happens if you don't click any button but open "Item A3" the usual way (clicking on it), then click above the buttons (lose focus) and then press several times the TAB key. I think it's a general drilldown focus management issue and may be related to this issue https://github.com/zurb/foundation-sites/issues/10429

2017-07-28 20:39 UTC, SassNinja commented
ping @kball  – would be great to get your feedback (in particular on the 1st point)

Besides I've noticed this PR and some others are broken, precisely its history.
- https://github.com/zurb/foundation-sites/pull/10404
- https://github.com/zurb/foundation-sites/pull/10456
- https://github.com/zurb/foundation-sites/pull/10394
- https://github.com/zurb/foundation-sites/pull/10408

Surprisingly everathing was fine when I looked into it last time and there haven't been pushes in the meantime (at least in my PRs).
Any idea what might have broken them?

2017-08-03 19:03 UTC, IamManchanda commented
Poke @kball ... Now what needs to bee done ?

2017-08-04 23:10 UTC, kball commented
@SassNinja with regards to the PRs getting wonky, unfortunately we had some issues with the develop branch... we've fixed those (and added protection to prevent future occurrences) but old PRs seem to still be a little wonky... going to try closing and reopening to see if that fixes it.

2017-08-04 23:14 UTC, kball commented
With regards to your questions - I think we can separate #2 into a differnet issue as I've inconsistently seen it in other situations... for #1 we generally don't show the focus ring for non-keyboard nav, so I'd say lets make the default no focus, and then this should be good to go.

Since it doesn't seem that closing and reopening fixed the history, I'm going to close entirely, can you try creating a new PR with these changes and the update above? Thanks!

2017-08-04 23:14 UTC, closed without merging