Modified Kitchen Sink Page
foundation/foundation-sites pull request #10500
Opened 2017-08-03 09:34 UTC by danclayton50

Added data-closable attribute to closable callout div so it closes properly

That's all!

2017-08-04 22:59 UTC, kball commented
Thanks for the PR! This makes the callout closable, but to get it to close, we need to make the close button also have a `data-close` attribute so it will trigger the appropriate event.

2017-08-05 09:27 UTC, danclayton50 commented
Thanks, done that now and it works!

2017-08-05 15:15 UTC, IamManchanda approved these changes

2017-08-05 15:16 UTC, IamManchanda requested changes

2017-08-05 15:16 UTC, IamManchanda commented on docs/pages/kitchen-sink.md
>    <p>This is a static close button example.</p>
I think you need to remove the word `static` ? No ?

2017-08-06 15:29 UTC, danclayton50 commented
Removed the word static.

2017-09-08 22:28 UTC, merged

2017-09-08 22:28 UTC, kball commented
Perfect! Merged, thanks @danclayton50!