Allow breakpoint mixin to accept a list
foundation/foundation-sites pull request #10939
Opened 2018-02-14 12:22 UTC by homerjam

This fixes the following issue whereby gutters aren't set as expected for larger sizes:
```
.my-cell {
      @include xy-cell(12);

      @include breakpoint(medium) {
        @include xy-cell(6/12);
      }
}
```

by allowing the following:
```
.my-cell {
      @include xy-cell(12);

      @include breakpoint(medium, large, xlarge, xxlarge) {
        @include xy-cell(6/12);
      }
}
```

Before submitting a pull request, make sure it's targeting the right branch:

- For documentation fixes, use `master`.
- For bug fixes or new features compatible with the next version, use `develop`.
- For bug fixes incompatible with `develop`, use the support branch of the latest compatible version, which will be formatted `support/6.x`.

If you're fixing a JavaScript issue, it would help to create a new test case under the folder `test/visual/` that recreates the issue and show's that it's been fixed. Run `npm test` to compile the testing folder.

Happy coding! :)

2018-02-14 14:51 UTC, DanielRuf commented
Isn't this more like a feature or really a bugfix?

2018-02-14 14:57 UTC, homerjam commented
I'm not sure to be honest, I couldn't figure out from #10141 and #10387 whether this was intentional behaviour or not.

2018-02-14 22:05 UTC, ncoden requested changes
Hi @homerjam,

Basically, this change allow to duplicate a `breakpoint()` content across several breakpoints.

For now `breakpoint()` only takes one size as parameter, since before `xy-grid` there was no reason to duplicate the same content across breakpoints. But now `xy-grid` automatically detect the breakpoint it is in, so this would be a legit use case.

However, I am afraid that not everyone will use it correctly and that many will end up duplicating a lot of code without knowing.

We could add that feature as is with a very good documentation. But I would like us to also look for others solutions.

Note: "request change" because the mixin documentation is not updated.

2018-02-15 11:03 UTC, homerjam commented
Hi @ncoden 

Glad to see this is being considered and you understand the use case.

I've briefly updated the inline documentation as requested.

For others possibly arriving here this is how I'm working around the issue for now:
```
.my-cell {
     @include xy-cell(12);

      @each $size in (medium, large, xlarge, xxlarge) {
        @include breakpoint($size) {
          @include xy-cell(6/12);
        }
      }
}
```

Thanks!

2018-02-18 16:23 UTC, ncoden approved these changes
Hi @homerjam. I made the following changes:

* [x] Use the arglist annotation instead of list
* [x] Add usage cases in the XY Grids docs
* [x] Add warning about code duplication

2018-02-18 20:48 UTC, DanielRuf approved these changes
lgtm.

Definitely helpful feature and the implementation seems is ok.

2018-02-20 11:04 UTC, homerjam commented
Awesome! Thanks @ncoden

2018-02-20 11:05 UTC, merged