fix: initialize sticky elements for dynamically loaded DOM, fixes #8016
foundation/foundation-sites pull request #10947
Opened 2018-02-15 23:47 UTC by DanielRuf

We have to check for `document.readyState === "complete"` when the window and content is already loaded and more content is loaded afterwards that is needed for the magellan and sticky solution.

2018-02-15 23:58 UTC, DanielRuf commented
Working codepen: https://codepen.io/DanielRuf/pen/LQOWmE

2018-02-17 22:30 UTC, ncoden commented
I just found the same issue with `Magellan`. There is probably others issues like this across all components. :/

2018-02-17 23:16 UTC, DanielRuf commented
Right, we may have to add this to some more components.

2018-02-17 23:18 UTC, DanielRuf commented
I'll check the other components, prepare an issue and collect them there and link the PRs then (I would rather go step for step or component for component to have better and more atomar changes which is easier for bisecting and regression testing imo).

2018-02-17 23:19 UTC, ncoden commented
I was going to take care of this and open a PR but ok, have fun ;)

2018-02-17 23:31 UTC, DanielRuf commented
> keeping everything in one PR is easier to manage.
Agreed. I'll prepare the other commits then. If you want you can also push to my branch. Or do we already have some PRs for the other components?

2018-02-17 23:41 UTC, ncoden commented
>  Or do we already have some PRs for the other components?

I don't think. There was PRs before that resolved some cases manually (and sometimes badly), but everything is merged by now.

2018-03-06 22:28 UTC, DanielRuf commented
Also see https://github.com/zurb/foundation-sites/issues/9047

2018-03-06 22:30 UTC, ncoden commented
Thanks.

2018-03-17 21:58 UTC, DanielRuf commented
Pushed a new commit. Did not find more occurences where we wait for the load event.

2018-03-17 22:05 UTC, ncoden commented
@DanielRuf Seen. LGTM but require some cleaning as said at https://github.com/zurb/foundation-sites/pull/10988#discussion_r171405136, maybe in an other PR (that or in that PR but with a squash after). Do you want to take care of this or should I ?

2018-03-17 22:28 UTC, DanielRuf commented
> LGTM but require some cleaning as said at #10988 (comment), maybe in an other PR (that or in that PR but with a squash after). Do you want to take care of this or should I ?

Would be glad if I couls get some assistance here so feel free to prepare a PR with the needed changes to make them all consistent then.

2018-03-18 20:53 UTC, ncoden requested changes

2018-03-18 20:53 UTC, ncoden commented on js/foundation.magellan.js
> +    }
> When  a Magellan component is dynamically created, the window DO NOT scroll  to the target corresponding to the location hash as the magellan did not  created the target and should appear without effects on it after the  page already loaded.
>
> -- https://github.com/zurb/foundation-sites/pull/11077#issue-175772567

2018-03-18 20:53 UTC, ncoden commented
Closing in favor of https://github.com/zurb/foundation-sites/pull/11077

2018-03-18 20:53 UTC, closed without merging