fix: IE 11 and older do not trigger popstate, use hashchange for chec…
foundation/foundation-sites pull request #11006
Opened 2018-03-02 21:57 UTC by DanielRuf

IE 11 and older do not trigger the `popstate` event when the hash changes.
We have to use `hashchange` in this case.

It is a bug that will not be fixed. See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/

Closes https://github.com/zurb/foundation-sites/issues/10771

2018-03-02 23:03 UTC, ncoden requested changes
Same as for others PRs: `popstate` is used a lot within the framework (Tabs, Accordion, Magellan, Reveal).

Please add an utility in `foundation.util.core` (or an other utility file if you think it is more appropriate) and avoid code duplication.

2018-03-02 23:17 UTC, DanielRuf commented
> Same as for others PRs: popstate is used a lot within the framework (Tabs, Accordion, Magellan, Reveal).
> 
> Please add an utility in foundation.util.core (or an other utility file if you think it is more appropriate) and avoid code duplication.

Good suggestion. Similar to the `load` utility method that you suggested?

2018-03-02 23:25 UTC, ncoden commented
@DanielRuf Exactly (with a better name, specific enough to Foundation)

2018-03-04 01:11 UTC, ncoden commented
@DanielRuf  I started implemented a generic `popstateEvent` and made some research:

* [hashchange](https://developer.mozilla.org/en-US/docs/Web/Events/hashchange) is triggered _only when the hash change_. It is not similar to `popstate` as it will not be triggered when the url change. __IE 8+__.
* [popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) is triggered when the history state is changed. __Edge 14+__.

But none of these events will not being triggerd by `history.pushState()` (see https://codepen.io/ncoden/pen/ddLQmN). Only backward/forward history manipulations will (like clicking on a link or called `history.back()`). There is a good polyfill [here](http://felix-kling.de/blog/2011/01/06/how-to-detect-history-pushstate/) but it works by overriding `history.pushState`.

The thing is: we do not even need to listen on all history change. We currently use `popstate` (checked for Accordion, Magellan, Reveal and Tabs) only for `window.location.hash`, and could rely on `hashchange` instead without any problems. No need for a polyfill.

2018-03-04 16:33 UTC, ncoden commented
Closing this in favor of https://github.com/zurb/foundation-sites/pull/11011

2018-03-04 16:33 UTC, closed without merging