chore: add multiple issue templates
foundation/foundation-sites pull request #11246
Opened 2018-05-07 21:49 UTC by ncoden

Closes https://github.com/zurb/foundation-sites/issues/11241

2018-05-07 22:10 UTC, ncoden commented
Poke @DanielRuf for review :)

2018-05-08 21:10 UTC, ncoden commented
Poke @DanielRuf for review :)

2018-05-08 21:46 UTC, DanielRuf approved these changes

2018-05-08 21:46 UTC, DanielRuf commented on .github/ISSUE_TEMPLATE/1-bug-report.md
> +## What happends instead?
happends => happens

2018-05-08 21:46 UTC, DanielRuf commented on .github/ISSUE_TEMPLATE/2-feature-request.md
> +<!--- Why would this feature benefits to everyone? What is the current      -->
benefits to => benefit

2018-05-08 21:46 UTC, DanielRuf commented on .github/ISSUE_TEMPLATE/4-maintainance.md
> +<!---  Only submit maintainance issue here. For help or questions to the.   -->
issue => issues

2018-05-08 21:46 UTC, DanielRuf requested changes
Some small typos.

2018-05-09 20:54 UTC, ncoden commented
@DanielRuf Fixed

2018-05-11 21:32 UTC, ncoden commented
poke @DanielRuf

2018-05-11 21:34 UTC, DanielRuf approved these changes

2018-05-11 21:36 UTC, merged