Clarify usage of body overflow hiding re .medium-grid-frame example in docs
foundation/foundation-sites pull request #11273
Opened 2018-05-16 21:03 UTC by paxperscientiam

## Description
Per PR #11191 and my own [comment](https://github.com/zurb/foundation-sites/issues/11191#issuecomment-389658664), I have added commentary warning re hiding body overflow.

## Motivation and Context
My motivation is to help others that may or may have blindly add `body{overflow:hidden;}` to their code per current suggestion and wind up with a webpage that won't scroll on small screens.

Hope that makes sense!

## Checklist (all required):

- [ x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [ x] There are no other pull request similar to this one.
- [ x] The pull request title is descriptive.
- [ x] The template is fully and correctly filled.
- [ ] The pull request targets the right branch (`develop` or `support/*`).
- [ ] My commits are correctly titled and contain all relevant information.
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).
- [ ] All new and existing tests passed.

2018-05-16 21:24 UTC, ncoden requested changes
TL;DR: XY Grid is already very heavy.

2018-05-16 21:25 UTC, ncoden commented
✨ Welcome back @paxperscientiam and thank you for your PR ✨

2018-05-16 21:54 UTC, paxperscientiam commented on docs/pages/xy-grid.md
> +  Given the `.medium-grid-frame` example below, you'll want to take care to hide overflow body content for medium and larger screens only.
Yes. Let me do that.

2018-05-16 22:10 UTC, ncoden commented
@paxperscientiam We updated our [CONTRIBUTING](https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md#contributions) recommendations. Please take a look at the "Contributions" sections, you'll find relevant stuff and advices for this pull request.

2018-05-16 22:17 UTC, ncoden commented
Looks good now.

> ed53c10 Update xy-grid.md
> 263bd99 Update xy-grid.md
> 50e1793 Update xy-grid.md
> 680ce8e Update xy-grid.md
> fbf6cfe [docs] Merged two paragraphs.
> d516233 [docs] Removed unncessary code examples

Could you squash commits ?

2018-05-16 22:17 UTC, ncoden commented
@paxperscientiam  Looks good now.

> ed53c10 Update xy-grid.md
> 263bd99 Update xy-grid.md
> 50e1793 Update xy-grid.md
> 680ce8e Update xy-grid.md
> fbf6cfe [docs] Merged two paragraphs.
> d516233 [docs] Removed unncessary code examples

Could you squash commits ?

2018-05-17 04:39 UTC, paxperscientiam commented
Hey @ncoden , I'm new to squashing, so not sure I did it correctly. Halp?

2018-05-17 05:09 UTC, DanielRuf commented
Squashing is basically a `git rebase` with `fixup` for all but the first commit which is reworded with `reword` added to this branch so that there is only one commit.

2018-05-17 05:42 UTC, ncoden commented
See https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

2018-05-17 21:07 UTC, DanielRuf approved these changes

2018-05-17 21:37 UTC, ncoden commented
> I just learned from #git on Freenode that this can be done automagically from within GH by whomever does the merging.

True but it can often be useful to get the author commits inside the Foundation branches (instead of squashing all of them), and I'd like to keep the "merge commit + author commit(s)" method consistent.

@DanielRuf I just discoverd that GitHub actually keeps all outdated changes inside their commits, even after the branch is "force pushed", merged and deleted. So we may not have to create new PRs, GitHub keeps everything.

2018-05-17 21:38 UTC, DanielRuf commented
I'll rebase your branch later.

Normally you just have to run `git rebase -i HEAD~13` and write `fixup` instead of `pick` for all but not the first commit. And then do `git commit --amend` to reword your first commit or use `reword` instead of `pick`.

2018-05-18 20:50 UTC, ncoden commented
Ok, I just seen that this PR was opened from `zurb:master`. I'll clean that.
@paxperscientiam Please create branches on your own fork of `foundation-sites` and open your pull requests from them. Do not make changes directly on the `foundation-sites` repo.

2018-05-18 21:06 UTC, closed without merging

2018-05-18 21:12 UTC, ncoden commented
See https://github.com/zurb/foundation-sites/pull/11280

2018-05-19 01:33 UTC, paxperscientiam commented
@ncoden My bad and will do!