feat: automatically pick active menu item color by contrast
foundation/foundation-sites pull request #11354
Opened 2018-06-26 22:59 UTC by vanilla-thunder

picking text color by contrast instead of hardcoded white for easier color scheme customisation

## Description
while active menu item **background** is taken from customizable color palette, it's **color** is still hardcoded to white and needs to be replaced manually to matching color. 

- Closes https://github.com/zurb/foundation-sites/issues/11353

## Motivation and Context
For easier color scheme customization the text color could be picked automatically by comparing color contrasts, like its done for styled buttons ( _buttons.scss line 140 ).

## Screenshots (if appropriate):

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to change)  

Imho, this PR is an improvement. Since auto-picking color by contrast is already implemented for styled buttons, i would expect the same behavior for other styled elements. Therefore the issue is kind of "unexpected behavior". I checked both "fix" and "new feature"

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] There are no other pull request similar to this one.
- [x] The pull request title is descriptive.
- [x] The template is fully and correctly filled.
- [x] The pull request targets the right branch (`develop` or `support/*`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).
- [x] All new and existing tests passed.

2018-06-27 20:14 UTC, ncoden requested changes
Hi @vanilla-thunder. Thank you so much for your first contribution 🎉 

We try to avoid unecessary renaming, and others things that would break our Sass users code. Please take a loot at the review comments below.

2018-06-27 20:14 UTC, ncoden commented on scss/components/_menu.scss
> +$menu-item-color: $white !default;
This would be a breaking change

2018-06-27 20:14 UTC, ncoden commented on scss/components/_menu.scss
> +$menu-item-color-alt: $black !default;
I think we should use `$menu-item-color-active` and `$menu-item-color-alt-active` for backward compatibility and concistency.

2018-06-27 20:15 UTC, ncoden commented
Planned for v6.6.0 as this is a new feature.

2018-06-28 10:22 UTC, ncoden commented
@vanilla-thunder Will you have time to discuss/provide the requested changes ?

**Note to myself**: maybe we could simplify the pull request "Checklist" and add a checkbox "I am availaible to discuss and work on this pull request later"

2018-06-28 11:59 UTC, vanilla-thunder commented
sure, sorry for letting you wait.

I had some additional thoughts about customizing menu colors, especially the regular menu item text, not only the active. Just in case someone would like to have different menu color than regular text color (e.g. when having dark navbar while the rest of the page is light), you might want to keep the original variable for active color, but also add variables for regular menu item color and alternative color for active menu item. 
Something like this:
````SASS
/// regular menu colors
$menu-item-color: $white !default;
$menu-item-color-alt: $black !default;
/// active item colors
$menu-item-color-active: $menu-item-color !default;
$menu-item-color-alt-active: $menu-item-color-alt !default;
````

So people who already configured own $menu-item-color-active will keep it.
What do you think about that?

Also, i found the same color picking bahavior in dropdown-menus, do you want me to make separate PR for dropdowns or add my changes into this PR?

2018-06-28 13:37 UTC, ncoden commented
For now, menus doesn't have a color set for their default state. If I understand your proposal correctly, it would change this color to $white. Is that what you mean ?

For the pull requests, please group all similar changes even across multiple components. It's easier for us to follow. Please update the pull request title and description.

2018-06-28 18:39 UTC, vanilla-thunder commented
please have a look at the changes, this should be finde now.
(forget my other suggestion, I accidentally looked into wrong files)

2018-06-28 19:04 UTC, ncoden approved these changes
LGTM. Could you squash everything ?

2018-06-28 23:20 UTC, ncoden commented
Thank you

2018-06-28 23:20 UTC, merged