fix: fix SmoothScroll not applying custom options
foundation/foundation-sites pull request #11622
Opened 2018-12-07 02:27 UTC by ben-z

## Description

SmoothScroll no longer takes into account the options passed in to its constructor because the event handler doesn't have the correct `this`. It worked prior to v6.5 because [before the refactor, the event handler uses `_this` from the closure instead of `this` directly](https://github.com/zurb/foundation-sites/blob/140abba37384784f2c6fc38d0ca8b1812c0eba16/js/foundation.smoothScroll.js#L47).

Please refer to https://github.com/zurb/foundation-sites/issues/11620 for a detailed description of this bug.

This PR binds `this` to the event handlers to solve the problem.

- Closes #11620

## Types of changes

- [ ] Documentation
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [ ] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [x] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

It's my first time contributing. As far as I know there aren't any unit tests for this, so I didn't add any tests for my changes. Please let me know if I need to do anything else for this PR!

2018-12-07 09:44 UTC, DanielRuf approved these changes

2018-12-07 10:29 UTC, ncoden requested changes
With `.bind()`, a new function will be created and attached to the event. So when we want to clear the handlers in `_destroy` with `this._handleLinkClick`, the function will not be detached from the event.

You could save `this._handleLinkClick.bind(this)` as `this._linkClickListenner` then reuse it in `_destroy` to clear it.

2018-12-07 21:11 UTC, ben-z commented
@ncoden good catch! Fixed as suggested. Since `_events` seems to only be called from the constructor, I don't think we need to worry about `this._linkClickListenner` being overwritten when there are multiple calls to `_events`.

2018-12-07 22:05 UTC, DanielRuf requested changes

2018-12-07 22:05 UTC, DanielRuf commented on js/foundation.smoothScroll.js
> +        this._linkClickListenner = this._handleLinkClick.bind(this);
Listener instead of Listenner

2018-12-07 22:12 UTC, ben-z commented on js/foundation.smoothScroll.js
> +        this._linkClickListenner = this._handleLinkClick.bind(this);
awks 😅. Fixed

2018-12-10 20:43 UTC, ncoden approved these changes
LGTM. Thank you @ben-z 👍

2018-12-10 20:44 UTC, ncoden commented
Waiting for @DanielRuf to approve the changes as well.

2018-12-10 21:46 UTC, DanielRuf approved these changes

2018-12-12 20:50 UTC, merged

2019-12-06 19:24 UTC, joeworkman commented
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-for-sites-v6-6-0-is-here-farout/30/1