chore: add npm script to link the docs
foundation/foundation-sites pull request #11838
Opened 2019-10-06 10:31 UTC by DanielRuf

## Description

This PR removes the shell script for linking the docs and adds a npm script for doing the same which is platform agnostic.

## Types of changes

- [ ] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (anything that would change an existing functionality)
- [x] Maintenance (refactor, code cleaning, development tools...)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The pull request title and template are correctly filled.
- [x] The pull request targets the right branch (`develop` or `develop-v...`).
- [x] My commits are correctly titled and contain all relevant information.
- [ ] I have updated the documentation accordingly to my changes (if relevant).
- [ ] I have added tests to cover my changes (if relevant).

2020-02-03 18:31 UTC, joeworkman commented on package.json
> +    "docs:link": "git clone https://github.com/zurb/foundation-docs && npm link ./foundation-docs"
Update this to be https://github.com/foundation/foundation-docs instead

2020-02-04 21:08 UTC, joeworkman requested changes
Update this to be https://github.com/foundation/foundation-docs instead

2020-02-05 02:54 UTC, joeworkman approved these changes

2020-02-05 02:55 UTC, joeworkman approved these changes

2020-02-05 02:59 UTC, merged

2020-02-05 05:20 UTC, DanielRuf reviewed
It seems this references still the old org. Did you update it @joeworkman?