appendTo feature for reveal
foundation/foundation-sites pull request #9094
Opened 2016-08-09 14:23 UTC by phifa

2016-09-23 06:45 UTC, Owlbertz commented on js/foundation.reveal.js
> +                    .appendTo('this.options.appendTo');
In order to have the code aligned I would like to see ` .appendTo($(this.options.appendTo));

2016-09-23 06:47 UTC, Owlbertz approved these changes
Seems like a useful feature to me.
Just one small think I commented on a line.
I would like to have feedback from another @zurb/yetinauts on that since it changes the public API.

2016-09-27 22:53 UTC, kball commented on js/foundation.reveal.js
> +                    .appendTo('this.options.appendTo');
I agree, putting it in the quotes won't work, because jquery will try to find that string, rather than the variable.

2016-09-27 22:55 UTC, kball requested changes
We need to change the overlay append to properly reference the appendTo variable rather than a string.

2016-09-27 22:55 UTC, kball commented on js/foundation.reveal.js
> +                    .appendTo('this.options.appendTo');
In fact, I think I need to change this to a review because without this change this PR is not correct.

2016-11-01 16:52 UTC, kball commented
I'm going to just do the update for the bug in place and get this merged

2016-11-01 16:54 UTC, merged