[Orbit] Detaches events on reInit
foundation/foundation-sites pull request #9278
Opened 2016-10-20 23:36 UTC by milose

Fixes #9245.

2016-10-31 21:49 UTC, kball requested changes
Broadly speaking, love the direction of this.  I'm a bit confused why some stuff is in the _detachEvents method, as it doesn't appear to be actually related to detaching events.  Would like those either pealed off into a different method or explain why they are a part of detach.

2016-10-31 21:49 UTC, kball commented on js/foundation.orbit.js
> +
A little confused why this is in _detachEvents

2016-10-31 21:49 UTC, kball commented on js/foundation.orbit.js
> +      this.$element.trigger('slidechange.zf.orbit', [this.$slides.first()]);
This also seems like it might be in the wrong place

2016-10-31 21:49 UTC, kball commented on js/foundation.orbit.js
> +        this._updateBullets(0);
and this as well.  Should these be in _init?  Or

2016-11-01 14:09 UTC, milose commented on js/foundation.orbit.js
> +
This is needed to reset the state of the component because of poorly implemented `changeSlide` method.

2016-11-01 14:09 UTC, milose commented on js/foundation.orbit.js
> +      this.$element.trigger('slidechange.zf.orbit', [this.$slides.first()]);
I am not sure this is necessary, but users might be listening to this event and by switching to the first slide, this must be triggered.

2016-11-01 14:14 UTC, milose commented
Perhaps we should rename `_detachEvents` to `_resetOrbit` or something similar, because it does more then detaches events.

2016-11-01 14:32 UTC, milose commented
Because of the poor implementation of `changeSlide` method, I was almost inclined to copy initial DOM of the Orbit in local state, then pull it back in if `_init` was called by `Foundation.reInit($orbit)`. That would also fix the issue but it is not an elegant solution. This proves that `changeSlide` method pollutes the DOM of the Orbit and needs to be changed in order for `_init` to do it's job without this pull request.

On the other hand, shy of `reInit`, the `changeSlide` method works as expected, and is battle-tested.

2016-11-01 15:55 UTC, kball commented
@milose I think if we change the function name to more semantically match all of its behavior (`_resetOrbit` works for me), I'm good with this PR, and it moves the ball forward.  Afterwards, if you want to work on another one that cleans up `changeSlide` that would be awesome! :)

2016-11-01 16:47 UTC, kball approved these changes

2016-11-01 16:47 UTC, merged