Drop menu fix for handling closeOnClickInside
foundation/foundation-sites pull request #9338
Opened 2016-11-07 14:25 UTC by sujayjaju

Fixes implementation of #9131 and includes a fix for #9293

2016-11-08 18:52 UTC, kball requested changes
Thanks for taking a pass on this @sujayjaju!  Travis turned up one typo to take a look at, but then we can get on to testing.

2016-11-08 18:52 UTC, kball commented on js/foundation.dropdownMenu.js
> +      }
I think you need a closing parens here

2016-11-08 18:52 UTC, kball commented on js/foundation.dropdownMenu.js
> +      }
Yeah, travis is breaking due to this.

2016-11-08 19:39 UTC, kball approved these changes

2016-11-11 16:35 UTC, merged

2016-12-14 15:00 UTC, forkiven commented on js/foundation.dropdownMenu.js
> +        var hasSub = $elem.hasClass(parClass);
Is it just me or is $elem not defined here. Are we missing a  `$elem = $(this)`?

2016-12-14 15:01 UTC, mikewuu reviewed
$elem undefined error

2016-12-14 15:44 UTC, ncoden commented on js/foundation.dropdownMenu.js
> +        var hasSub = $elem.hasClass(parClass);
Yes.

2016-12-14 17:06 UTC, kball commented
Yes, this was caught in QA and has been fixed in the 6.3 branch - see: https://github.com/zurb/foundation-sites/pull/9472/files