Frame Grid
foundation/foundation-sites pull request #9487
Opened 2016-12-09 22:34 UTC by zurbrandon

Taking the best parts of the Foundation for Apps grid and adding it into sites as an optional extension of the grid.

Meant to work in conjunction with the Foundation for Sites grid or flex grid, but act as the outer shell of a complex web app layout.

This WIP is mainly complete for features of the grid overall and the docs should be about 75% there. Still need some additional browser testing and some improvements to the docs demos. Could also benefit from a template to better show the power of deep nesting with this grid.

Still to do in the wishlist would be the Panel functionality we had developed for Apps. Where on smaller screens a frame-block or frame-group could be made fixed position and triggered as a panel on from off screen. This syntax could use some help and the actual trigger would be need to created using JS. This however was a HUGE help in the Foundation for Apps grid, as it allowed me to have 2-3 columns share horizontal space on large screens, but then have less important content called from off screen on smaller screens.

Looking for help pushing this past the finish.

2016-12-09 22:39 UTC, kball commented
Thanks @zurbrandon for getting this together before you depart!  @zurb/yetinauts lets pick this up and get it to happen for 6.4.  @brettsmason given all of the learning you had on off canvas recently I have a suspicion you might have some thoughts on the panels idea

2016-12-09 22:42 UTC, zurbrandon commented
The Functionality is pretty set in apps, but i think the syntax could use some change. @brettsmason This is much easier than the off-canvas since you don't need to transition the body too. Just push the div off on small and translate it on when triggered.

2016-12-10 03:51 UTC, paxperscientiam commented
@zurbrandon Really great to see this coming to Foundation for Sites -- great work! Up until now, I've been using custom mixins to handle vertical "blocking". 

I'm playing around with your code and it seems that the `order` classes are not yet in source. That is, they at least do not appear in compiled CSS.

2016-12-11 09:52 UTC, DaSchTour requested changes
There are some mixins that could be taken from grid/flex-grid or util/flex

2016-12-11 09:52 UTC, DaSchTour commented on scss/grid/_apps-grid-modifiers.scss
> +@mixin grid-align($align: left) {
Similar to flex-align from util/flex

2016-12-11 09:52 UTC, DaSchTour commented on scss/grid/_apps-grid-modifiers.scss
> +@mixin grid-size($size: expand) {
Similar to flex-grid-column from grid/flex-grid

2016-12-11 09:52 UTC, DaSchTour commented on scss/grid/_apps-grid-modifiers.scss
> +@mixin grid-orient($orientation: horizontal) {
Similar to flex-direction from util/flex

2016-12-11 09:52 UTC, DaSchTour commented on scss/grid/_apps-grid-modifiers.scss
> +@mixin grid-order($order: 0) {
The same as flex-order from util/flex

2016-12-11 20:59 UTC, brettsmason commented
@zurbrandon sorry for the delay - I'll take a look at this tomorrow night and get back to you.
Looks like @DaSchTour and @paxperscientiam have both been actively looking at it and given great feedback already!

2016-12-12 17:13 UTC, kball commented
So you guys know, @zurbrandon is no longer going to be able to put substantial time into Foundation - he hustled to get as much of this in place as possible before he was leaving.

What this means is, if anyone is *excited* about taking this on, improving, polishing, etc... it's wide open! 😁

2017-04-14 23:41 UTC, kball commented
@ncoden are you still interested in doing the finishing work here?

2017-04-28 03:08 UTC, corysimmons commented on docs/pages/frame-grid.md
> +<div class="frame-grid-sample vertical frame">
Doesn't this need wrapped in triple quotes?

2017-05-22 23:18 UTC, kball commented
@brettsmason @corysimmons Did we more or less decide this was being taken care of by the new grid in https://github.com/zurb/foundation-sites/pull/10017 ?

2017-05-23 17:56 UTC, corysimmons commented
tbh I'm not exactly sure what Brett decided on the vertical stuff. Is that going into #10017 ?

Either way, this one can probably be closed and Brandon can raise feature requests in #10017

2017-05-24 23:52 UTC, kball commented
After digging through this again, I'm pretty convinced that all of the functionality achieved within this will be a part of @brettsmason's new grid, but going to leave this open until that is a little more complete so we can compare

2017-06-03 20:40 UTC, kball commented
Closing this as the core ideas were incorporated into the XY grid

2017-06-03 20:40 UTC, closed without merging