Update foundation.d.ts
foundation/foundation-sites pull request #9616
Opened 2017-01-08 13:46 UTC by stcp

Updated some options.
Added ResponsiveMenu and ResponsiveToggle types.
Added defaults to all plugins.

2017-01-08 16:07 UTC, IamManchanda commented
i hate this travis ci .... i must say ..... network connectivity issues always

2017-01-09 08:26 UTC, DaSchTour requested changes
Why are there so many empty interfaces?

2017-01-09 08:26 UTC, DaSchTour commented on dist/js/foundation.d.ts
> +    patterns?:{[key:string]:RegExp};
I'm not sure if this will provide any already present pattern.

2017-01-09 08:26 UTC, DaSchTour commented on dist/js/foundation.d.ts
> +  interface AccordionDefaults extends IAccordionOptions{
Empty interface? So why not reference IAccordionOptions directly. From my look on the JS I'm also not sure if Defaults and options are the same. From what I see they are not.

2017-01-09 08:26 UTC, DaSchTour commented on dist/js/foundation.d.ts
> +  interface AccordionMenuDefaults extends IAccordionMenuOptions{
Empty interfaces?

2017-01-09 08:26 UTC, DaSchTour commented on dist/js/foundation.d.ts
> +    disableHover?: number;
Documentation says this is a boolean. http://foundation.zurb.com/sites/docs/tooltip.html

2017-01-09 08:26 UTC, DaSchTour commented on dist/js/foundation.d.ts
> -  interface AbideDefaults {
Why this is removed? This are the default properties.

2017-01-26 22:56 UTC, kball commented
@DaSchTour @stcp what is the status of this PR?

2017-04-19 08:47 UTC, DaSchTour commented
@kball I think we shouldn't change anything here. We should do the work to shift to TypeScript and get full typings from there.

2017-04-19 16:46 UTC, kball commented
@DaSchTour Given we'll likely do at least one more release (6.4) prior to any sort of TypeScript shift, are our current typings good enough? We're likely looking at July for 6.5

2017-04-19 19:41 UTC, DaSchTour commented
@kball I work with them regularly and they serve well. I'm note sure about the changes made here and the consequences they may have and the author didn't answer any of my questions :/

2017-04-19 20:16 UTC, kball commented
Seems reasonable. Closing in lieu of any additional responses indicating why we'd need these.

2017-04-19 20:16 UTC, closed without merging