Add docs about new git workflow
foundation/foundation-sites pull request #9665
Opened 2017-01-17 19:31 UTC by ncoden

Changes:
- Add docs about the branches of the new git workflow in `CONTRIBUTING.md`
- Update GitHub pull request template

2017-01-17 19:39 UTC, kball requested changes
One final piece of feedback, lets note that this workflow has been adopted as of 6.3, so folks don't ask about a support/6.2 branch etc

2017-01-17 19:39 UTC, kball commented on CONTRIBUTING.md
> +## Git Worflow
Typo -  Workflow not 'Worflow'

2017-01-17 19:39 UTC, kball commented on CONTRIBUTING.md
> +- **`develop`**: The developing branch used to prepare the next version. It always contains all the new features and bug fixes previously made, and constitutes the more up-to-date version of Foundati
Should we highlight that these are major/minor versions? To make clear that 'version' doesn't refer to patch versions...

Also, English feedback: "more up-to-date" => "most up-to-date". "now target the next" => "now targets the next"

2017-01-17 19:41 UTC, ncoden commented on CONTRIBUTING.md
> +- **`develop`**: The developing branch used to prepare the next version. It always contains all the new features and bug fixes previously made, and constitutes the more up-to-date version of Foundati
You are right.

2017-01-17 21:50 UTC, kball commented
This makes sense to me, can I get another review from someone on @zurb/yetinauts to make sure this seems clear to you and communicates our new process?

2017-01-24 06:42 UTC, IamManchanda commented
so now new features will go to develop ..... ?

2017-01-24 14:02 UTC, ncoden commented
@IamManchanda Yes.

@zurb/yetinauts Someone to review it ?

2017-01-24 16:49 UTC, colin-marshall commented
@ncoden @kball looks good to me!

2017-01-25 21:53 UTC, merged