.align-central as new alignment class
foundation/foundation-sites pull request #9701
Opened 2017-01-25 22:51 UTC by paxperscientiam

Hello,

I've written a new class named `.align-central` for the flex-grid. It does both vertical centering -- `.align-middle` -- and horizontal centering -- `.align-center`.

I made sure to leverage extant mixins.

2017-01-26 01:06 UTC, kball commented
Oooh I like it. @rafibomb what do you think?

2017-01-26 04:21 UTC, IamManchanda commented
Fallowing the convention that foundation uses .... I will go for `align-center-middle` to not complicate it much

2017-01-26 04:56 UTC, IamManchanda requested changes
This below will help with no complications and better convention .... Center and central are so similar that it get's hard to understand the use case of which is what

Poke @kball what do you think 

--------------------------------------------------------------------------------------------------------------

@paxperscientiam after its gets finalized, 
It will be great if you can provide a quick doc update too!
All in all, a very good addition to foundation.... thanks!!

2017-01-26 04:56 UTC, IamManchanda commented on scss/components/_flex.scss
> +    @include flex-align($y: 'middle');
Please rename to `align-center-middle`

2017-01-26 07:13 UTC, IamManchanda commented on scss/components/_flex.scss
> +    @include flex-align($y: 'middle');
Also, Please change the internal scss to this below 

```scss
.align-center-middle {
    align-content: center;
    @include flex-align($x: center, $y: middle);
 }
```
Ref. => http://foundation.zurb.com/sites/docs/flexbox.html#helper-mixins

2017-01-26 17:13 UTC, kball commented
I tend to concur with @IamManchanda `.align-center-middle` is more explicit and less likely to confuse

2017-01-26 17:40 UTC, IamManchanda commented
> I tend to concur with @IamManchanda `.align-center-middle` is more explicit and less likely to confuse

So @paxperscientiam, Review no.3 
Rename the title of this PR too apart from the commit :smiling_imp:

2017-01-26 17:46 UTC, paxperscientiam commented
@IamManchanda @kball Thanks for the input -- I'm on it!

2017-01-26 17:54 UTC, IamManchanda commented
=> **/docs/pages/flexbox.md**

Add this after (next in order) to [horizontal](http://foundation.zurb.com/sites/docs/flexbox.html#horizontal-alignment) and [vertical](http://foundation.zurb.com/sites/docs/flexbox.html#vertical-alignment) alignment and just above [Helper classes](http://foundation.zurb.com/sites/docs/flexbox.html#vanilla-flexbox-helper-classes) 

& I am unsure about the title @paxperscientiam @kball  .....

2017-01-26 19:25 UTC, rafibomb commented
I love it! `.align-center-middle` is pretty good.

2017-01-27 23:40 UTC, paxperscientiam commented
After @IamManchanda told me to RTFM (lol), it dawned on me that this class should probably be complemented with a "-self-" class.

EG:
````css
.align-self-center-middle {
 align-self: center;
 margin: 0 auto;
}

I'll whip it up, but please disabuse me of this notion if it's actually needless.

2017-01-28 01:57 UTC, IamManchanda commented
@paxperscientiam `align-self-middle` is almost solving the same thing .....
Can you explain what extra are you doing/providing with that dreaded `margin: auto` ?

2017-01-28 02:33 UTC, paxperscientiam commented
@IamManchanda Given a maximally agnostic parent (align-content default is stretch) I don't believe a flex item can be centered without `margin: auto`.

In either case, I should keep this PR atomic. Rolling back...

2017-01-28 04:08 UTC, paxperscientiam commented
OK, updated `flexbox.md`.

2017-01-29 09:46 UTC, IamManchanda requested changes

2017-01-29 09:46 UTC, IamManchanda commented on docs/pages/flexbox.md
> +  <div class="columns">As above, though I share the center-middle with my siblings.
You forgot to close the div... this is breaking the page layout

2017-01-29 09:47 UTC, IamManchanda commented
@paxperscientiam Would request you to always please check locally before pushing changes. Your `flexbox.md` file had some errors both from written docs and coding perspective 

and sorry but as it was hard for me, to review the corrections and suggest changes line by line .... 
I have **FTFY** .... Please find the file below and update it with your current `flexbox.md` and then push the file again. Thanks .... Harry!

=> https://gist.github.com/IamManchanda/ab4b6d6d84152caa240a281f51a06c0a

2017-01-30 19:32 UTC, IamManchanda commented
Expecting a commit @paxperscientiam ?

2017-01-31 00:07 UTC, paxperscientiam commented
Sorry, I've been swamped. Will try to push today.

2017-01-31 12:14 UTC, IamManchanda commented
No issue ..... @paxperscientiam ..... actually i wanna do a Pull request that includes this portion but i can't do that unless this is merged ... So that's why i am awaiting this merge !

2017-02-01 05:40 UTC, IamManchanda commented
@paxperscientiam you updated old file again ..... did you replace the file with my given file??
=> https://gist.github.com/IamManchanda/ab4b6d6d84152caa240a281f51a06c0a

Are you finding any difficulty in the same???

2017-02-01 19:28 UTC, paxperscientiam commented
@IamManchanda I hadn't noticed your file. Thanks. Let me put that in there. brb

2017-02-01 19:59 UTC, IamManchanda commented
@paxperscientiam As you mentioned me on commit, for your personal benefit 

> Please use semantic names for commit/issues/PRs. It should describe the changes you made (with a complete description for commits), and not what you personally done.
> 
> :white_check_mark: Good:
> 
> 1. Renamed `align-central` to `align-center-middle`
> 2. Moved `align-center-middle` code to a mixin
> 3. Fix #xxx - Correct wrong variable name in `align-center-middle`
> 
> :x: Bad:
> 
> 1. Update Central alignement
> 2. **Apply changes asked by @someone**
> 3. I fixed #xxx, Yay!!
> 4. Here some changes, btw beautiful weather today, isn't it

2017-02-01 20:21 UTC, IamManchanda approved these changes
LGTM 
@kball for final review!

2017-02-01 20:22 UTC, paxperscientiam commented
@IamManchanda 

> > Please use semantic names for commit/issues/PRs.

Is that lesson just for future application or do you want me to update the commit message?

2017-02-01 21:24 UTC, IamManchanda commented
> > Please use semantic names for commit/issues/PRs.
> 
> Is that lesson just for future application or do you want me to update the commit message?

Keep it like this only for the time being .... let kevin sir decide on it!

2017-02-03 16:39 UTC, IamManchanda commented
Ping @kball ..... awaiting final review ??

2017-02-03 17:39 UTC, merged

2017-02-03 17:39 UTC, kball commented
Great work, merged!