Indicate proper way to check for switch value.
foundation/foundation-sites pull request #9774
Opened 2017-02-13 14:38 UTC by jellisii

There have been tickets in the past that indicated that checking the value of the underlying input for a switch is not obvious.  Added documentation to clarify said check.

Before submitting a pull request, make sure it's targeting the right branch:

- For documentation fixes, use `master`.
- For bug fixes or new features compatible with the next version, use `develop`.
- For bug fixes incompatible with `develop`, use the support branch of the latest compatible version, which will be formatted `support/6.x`.

If you're fixing a JavaScript issue, it would help to create a new test case under the folder `test/visual/` that recreates the issue and show's that it's been fixed. Run `npm test` to compile the testing folder.

Happy coding! :)

2017-02-13 16:11 UTC, IamManchanda requested changes

2017-02-13 16:11 UTC, IamManchanda commented on docs/pages/switch.md
>  ```html_example
Give a line space b/w closing div and ```html_example 
This is breaking the page layout

2017-02-13 16:13 UTC, IamManchanda commented on docs/pages/switch.md
> +<div class='primary callout'>
All the primary callouts should come first and then the warning callouts

2017-02-13 19:26 UTC, rafibomb commented
This is good, and I think that this components needs even more explanation of how it works. Would you mind if I jump into the PR and add some more?

2017-02-13 19:40 UTC, jellisii commented
Updates requested by @IamManchanda should be in place.  

@rafibomb, go for it.  I made this PR because I got tripped up by it this morning.

2017-02-14 05:59 UTC, IamManchanda approved these changes
Approving current changes 
ofcourse @rafibomb will add some more 

**Update**: This below link reference is by mistake .... :arrow_double_down:

2017-02-28 21:07 UTC, kball commented
@rafibomb is this still on your radar?

2017-04-25 21:09 UTC, kball commented
Going to just go ahead and merge this. Additional updates can be done at a later time. Thanks @jellisii!

2017-04-25 21:09 UTC, merged