Allow table stack breakpoint to be set with a variable
foundation/foundation-sites pull request #9777
Opened 2017-02-14 02:50 UTC by mwitek

Adding a var to set the breakpoint for stacked tables.

2017-02-14 05:55 UTC, IamManchanda requested changes
Poke @kball Settings again :D 
#Dist

2017-02-14 05:55 UTC, IamManchanda commented on scss/settings/_settings.scss
> +$table-stack-breakpoint: medium;
Setting files is generated automatically .....  

You need to add this variable here after this => https://github.com/mwitek/foundation-sites/blob/dbea7aa151d175f2f3db6bf7379d7bddec1d60c9/scss/components/_table.scss#L73

Please remove changes from settings!

2017-03-02 00:47 UTC, mwitek commented
@IamManchanda Ready for another look.

2017-04-03 21:17 UTC, kball commented
Looks good to me!

2017-04-03 21:17 UTC, merged