Fix for [Sticky] failes to init and remove html markup #8156
foundation/foundation-sites pull request #9804
Opened 2017-02-22 15:13 UTC by randmanrjr

I am submitting this pull request for the following issue: [https://github.com/zurb/foundation-sites/issues/8156](https://github.com/zurb/foundation-sites/issues/8156)

2017-02-22 16:01 UTC, IamManchanda commented on js/foundation.sticky.js
> +      }
Proper indentation please ??

2017-02-22 16:02 UTC, IamManchanda requested changes

2017-02-22 16:02 UTC, IamManchanda commented on js/foundation.sticky.js
> +      } else {
@randmanrjr Proper indentation please ??

2017-02-22 18:20 UTC, IamManchanda commented on js/foundation.sticky.js
> +        this.$container = $parent;
@randmanrjr Still need a bit more indentation fix 
=>  If confused, compare line 39 and 42 !

{{ Yes i am annoying :smile: }}

2017-02-22 20:03 UTC, randmanrjr commented on js/foundation.sticky.js
> +        this.$container = $parent;
No problem. Code style and quality control are important :-)

2017-02-23 10:29 UTC, IllusionPerdu commented on js/foundation.sticky.js
> +    if($parent.lenth){
Why you don't use the `if (!$parent.length) {}` in line 38 ?

2017-03-03 19:35 UTC, kball commented on js/foundation.sticky.js
> +    if($parent.lenth){
typo - length

2017-04-04 16:55 UTC, merged

2017-04-04 16:55 UTC, kball commented
Merged!  Thanks @randmanrjr! Congrats on first PR merged!

2017-04-05 02:34 UTC, randmanrjr commented
@kball, You're most welcome! I use Foundation every day, so it's nice to be able to give back some love.