The gimbal mixin maintains semantic property of flex mixin attributes
foundation/foundation-sites pull request #9862
Opened 2017-03-10 03:30 UTC by paxperscientiam

So, how to explain this?

As indicated in issue  #9837, the new and handy flex mixins -- though helpful -- become difficult to use with, for instance, `flex-direction: column`. Because the mixin argument-value pairs for `@mixin flex-align(...)` are biased in favor of `flex-direction: column`, the semantic meaning is lost/confused with `flex-direction: column`.

I put together a rough cut of what I am calling the "gimbal" mixin. It allows for the 'top', 'bottom', 'left', 'right', etc attribute values to retain their semantic value irrespective of flex direction.

This is just a draft and I would like some input on how "justify" and "spaced" should relate to "stretch". [linky](http://foundation.zurb.com/sites/docs/flexbox.html#flex-align).

2017-03-10 15:26 UTC, IamManchanda reviewed
Please look into it!

2017-03-10 15:26 UTC, IamManchanda commented on scss/components/_flex.scss
> +);
Indentation !!!

2017-03-10 15:26 UTC, IamManchanda commented on scss/components/_flex.scss
> +@mixin gimbal($o:row,$x:left,$y:top) {
Why the word "Gimbal" ?

2017-03-10 15:26 UTC, IamManchanda commented on scss/components/_flex.scss
> +}
Why this is here ?
No example css/scss please within here ?

--------------------------------------------------------------------------------------------------------

Although yes, this arise a question on how do you push a testing sass mixins

2017-03-10 20:37 UTC, paxperscientiam commented on scss/components/_flex.scss
> +@mixin gimbal($o:row,$x:left,$y:top) {
"Orientation" of natural directions remains constant regardless of whether or not the flex container flexes row or flexes column :)
[real world example](https://www.youtube.com/watch?v=29qeHVT-8-I)

2017-03-10 20:38 UTC, paxperscientiam commented on scss/components/_flex.scss
> +);
Oh, I know. I will fix this at the end -- after all the technical stuff is sorted out.

2017-03-10 20:41 UTC, paxperscientiam commented on scss/components/_flex.scss
> +}
That will definitely be deleted! Just there for testing purposes.

> ...example css/scss please...

Good idea, I will add that.

2017-03-11 14:43 UTC, IamManchanda commented on scss/components/_flex.scss
> +@mixin gimbal($o:row,$x:left,$y:top) {
Perfect then ....

2017-03-11 23:06 UTC, paxperscientiam commented on scss/components/_flex.scss
> +@mixin gimbal($o:row,$x:left,$y:top) {
Possibly better to call it `flex-gimbal`.

2017-03-12 04:50 UTC, IamManchanda commented on scss/components/_flex.scss
> +@mixin gimbal($o:row,$x:left,$y:top) {
Yeah `flex-gimbal` will be better

2017-03-13 19:06 UTC, paxperscientiam commented
OK, so I made the recommended changes. With regard to other flex-align options, still thinking.

2017-03-14 08:01 UTC, IamManchanda requested changes

2017-03-14 08:01 UTC, IamManchanda commented on scss/components/_flex.scss
> +// }
Please remove these comments

2017-03-14 14:11 UTC, DaSchTour commented on _vendor/normalize-scss/sass/normalize/_normalize-mixin.scss
> +      font-family: $base-font-family; /* 1 */
I guess this doesn't belong here. Looks like another topic and should be discussed in a separate thread.

2017-03-17 18:30 UTC, paxperscientiam commented
This is off topic @IamManchanda , but do you know if anyone is paying attention to foundation-cli?

I submitted a PR with minor fixes, but I am interested in submitting more.

2017-03-17 19:34 UTC, IamManchanda commented
@paxperscientiam it [happens](https://github.com/zurb/foundation-zurb-template/pull/53) bro

2017-04-04 16:45 UTC, kball commented
@rafibomb can you take a look at this?

2017-05-03 17:12 UTC, IamManchanda commented on scss/components/_flex.scss
> +// }
Please Remove these comments chris

2017-05-15 21:57 UTC, paxperscientiam commented on scss/components/_flex.scss
> +// }
@IamManchanda sorry. done.

2017-05-19 18:13 UTC, kball commented
@paxperscientiam can you write up some info on what exactly this is and how to use it, probably on the flexbox doc page under helpers?

2018-02-18 22:01 UTC, DanielRuf commented
Some info about this in the docs might be very helpful.

@paxperscientiam do you need any assistance with this?

2018-02-27 05:52 UTC, paxperscientiam commented
@DanielRuf I would/could if I had the time. Would you like the PR? I don't know if there's an official way, but I could close and would have no problem with you copying the code.

2018-02-27 06:14 UTC, DanielRuf commented
We can push changes to your branch.
Let's check together what we need in the docs.

How could this be best described for the docs or written?

2018-02-28 06:03 UTC, paxperscientiam commented
> How could this be best described for the docs or written?

I'd say something along the lines that `@mixin flex-gimbal(orientation, x, y)` frees devs from having to conceptualize a rotated coordinate system. That is, "x" (horizontal), means "x" irrespective if flex is row or column.

Does that make sense or help? Were you able to play with the code?

2019-07-24 22:28 UTC, kball commented
I'm going to close this for now as it was never finished out and we're trying to consolidate up fixes and outstanding PRs for F6 now that ZURB is releasing more control to the community. We can reconsider for F7.

2019-07-24 22:28 UTC, closed without merging