Forms-reset by normalize-scss overwrite button font-family
foundation/foundation-sites pull request #9915
Opened 2017-03-29 14:32 UTC by artursopelnik

*Problem:*
Forms-reset by normalize-scss overwrite button font-family. See on line 422, /_vendor/normalize-scss/sass/normalize/_normalize-mixin.scss.

*Example:*
$body-font-family: Verdana;
<button>Example Button</button>
Result: sans-serif

*Solution:*
Adding $button-font-family as similar to /scss/forms/_text.scss.

2017-03-29 15:31 UTC, IamManchanda requested changes

2017-03-29 15:31 UTC, IamManchanda commented on scss/components/_button.scss
> +$button-font-family: inherit !default;
Use that settings ( below review ) thing here

```scss
$button-font-family: $body-font-family;
```

2017-03-29 15:31 UTC, IamManchanda commented on scss/settings/_settings.scss
> +$button-font-family: $body-font-family;
Setting file is generated automatically ,
You dont need to add here!

2017-03-29 19:36 UTC, artursopelnik commented on scss/settings/_settings.scss
> +$button-font-family: $body-font-family;
Perfect :)

2017-03-29 19:37 UTC, artursopelnik commented on scss/components/_button.scss
> +$button-font-family: inherit !default;
Perfect :)
- using $body-font-family has fix that too ...

2017-04-17 20:30 UTC, merged

2017-04-17 20:30 UTC, kball commented
Went ahead and made teh settings fix myself, and merged.