pseudo spelling correction
foundation/foundation-sites pull request #9923
Opened 2017-04-02 11:38 UTC by dragthor

http://www.thefreedictionary.com/pseudo

2017-04-02 18:53 UTC, IamManchanda requested changes

2017-04-02 18:53 UTC, IamManchanda commented on dist/js/foundation.js
> + * Method for adding pseudo drag events to elements *
Dist files are automatically generated 
You should be editing source files instead 

Here are the files/lines where you should edit,
=> https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.touch.js#L79
=> https://github.com/zurb/foundation-sites/blob/develop/js/foundation.sticky.js#L108
=> https://github.com/zurb/foundation-sites/blob/develop/js/foundation.sticky.js#L149

2017-04-03 12:57 UTC, dragthor commented
Yeah, I know.  `dist` is under version control.  Maybe they should `.gitignore` it?

2017-04-03 13:09 UTC, IamManchanda commented
no,, not at all ... what about those who download css/js only version instead of compiled one ??

2017-04-17 20:43 UTC, kball commented
Dist files are updated at release time, and we dont' want them to change between releases... happy to take the comment updates for the sourcefiles alone if you can update.

2017-05-19 17:11 UTC, IamManchanda commented
@kball as @dragthor didn't reverted .... i did it .... please merge it!

2017-05-19 17:57 UTC, kball commented
👍

2017-05-19 17:57 UTC, merged