[New Feature] Closes #9870 - Added a combo pattern `website`
foundation/foundation-sites pull request #9984
Opened 2017-04-22 13:31 UTC by IamManchanda

Closes #9870 - Added a combo pattern `website`
Poke @kball for review and merge!

Changes:
- Added a pattern `website` which is basically a combo of both `domain` and `url` pattern
- Also updated the docs!

![website-pattern](https://cloud.githubusercontent.com/assets/4970624/25304883/ecef3104-278d-11e7-85ea-eaa5a6661a32.png)

2017-04-22 13:59 UTC, Deckluhm requested changes

2017-04-22 13:59 UTC, Deckluhm commented on docs/pages/abide.md
> +These input types create a text field: `text`, `date`, `datetime`, `datetime-local`, `email`, `month`, `number`, `password`, `search`, `tel`, `time`, `url`, `website` and `week`. Note the use of the
`website` isn't a valid input type: https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input#attr-type

2017-04-22 14:27 UTC, IamManchanda commented on docs/pages/abide.md
> +These input types create a text field: `text`, `date`, `datetime`, `datetime-local`, `email`, `month`, `number`, `password`, `search`, `tel`, `time`, `url`, `website` and `week`. Note the use of the
Oh sorry ... @Deckluhm ... mah bad ,,,,

2017-04-22 14:30 UTC, IamManchanda commented
@Deckluhm Thanks for your review ... i have updated ... check now!

2017-04-24 13:44 UTC, Deckluhm approved these changes

2017-04-24 16:09 UTC, kball commented on docs/pages/abide.md
> -        <input type="text" placeholder="http://foundation.zurb.com" pattern="url">
We should probably still highlight the URL pattern in the docs - can we add website as an additional rather than a replacement?

2017-04-24 16:14 UTC, IamManchanda commented on docs/pages/abide.md
> -        <input type="text" placeholder="http://foundation.zurb.com" pattern="url">
Ohkk !!! Sure!

2017-04-24 16:30 UTC, IamManchanda commented
done @kball .... please check again!

2017-04-25 21:01 UTC, kball commented
Looks good! Nice work @IamManchanda

2017-04-25 21:01 UTC, merged